server:
  port: 8091
spring:
  application:
    name: server-video
  http:
      encoding:
          charset: UTF-8
          enabled: true
          force: true
  messages:
      encoding: UTF-8
  mvc:
      servlet:
          load-on-startup: 1

mybatis-plus:
 # 扫描 mapper.xml
  mapper-locations: classpath:/mapper/*/*Mapper.xml

#拦截白名单
Interceptor:
  url-exclude: /user/login;/buy/notify;/health/info;

#log配置文件
logging:
  config: classpath:logback-spring.xml