eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: service-zuul

zuul:
  host:
    socket-timeout-millis: 3000
    connect-timeout-millis: 500
  routes:
    api-a:
      path: /mini-ser/**
      serviceId: server-video
    api-b:
      path: /doctor-ser/**
      serviceId: server-doctor
#拦截白名单
Interceptor:
  url-exclude: /user/login;/user/logout;/buy/notify;/health/info;

#log配置文件
logging:
  config: classpath:logback-spring.xml
  level:
    com:
      netflix:
        discovery: info
    org:
      apache:
        http: info