eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  host:
    socket-timeout-millis: 3000
    connect-timeout-millis: 500
  routes:
    api-a:
      path: /mini-ser/**
      serviceId: server-video
    api-b:
      path: /doctor-ser/**
      serviceId: server-doctor

#log配置文件
logging:
  config: classpath:logback-spring.xml
  level:
    com:
      netflix:
        discovery: info
    org:
      apache:
        http: info